image_root: '/shared/nas/data/m1/wangz3/Shared_Datasets/VL/COCO/images'
ann_root: '/shared/nas/data/m1/wangz3/Shared_Datasets/VL/COCO/annotations'
dataset: 'coco_with_grouping'
# pre-computed grouping files
image_id_groups: '/shared/nas/data/m1/wangz3/video_language_pretraining_project/BLIP/data_engineering/grouping/coco_retrieval_trainset-v_1000_t_8/image_id_groups.json'
image_id_2_data: '/shared/nas/data/m1/wangz3/video_language_pretraining_project/BLIP/data_engineering/grouping/coco_retrieval_trainset-v_1000_t_8/image_id_2_data.json'
k1: 1000
k2: 8
if_use_all: False


# set pretrained as a file path or an url
pretrained: '/shared/nas/data/m1/wangz3/video_language_pretraining_project/BLIP/ckpt/pretrained/model_base.pth'

# size of vit model; base or large

vit: 'base'
batch_size_train: 1 # pre-computed groups already batched, batch size equal to k2
batch_size_test: 64
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 1e-5

# vit: 'large'
# batch_size_train: 16
# batch_size_test: 32
# vit_grad_ckpt: True
# vit_ckpt_layer: 12
# init_lr: 5e-6

image_size: 384
queue_size: 57600
alpha: 0.4
k_test: 256
negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 1 # original 6



